OnTheHook/OnTheHook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path(
        "",
        include("homepage.urls"),
    ),
    path(
        "auth/",
        include("users.urls"),
    ),
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("social_django.urls"),
    ),
    path(
        "catalog/",
        include("catalog.urls"),
    ),
    path(
        "moderation/",
        include("moderation.urls"),
    ),
    path(
        "map/",
        include("map.urls"),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

OnTheHook/catalog/urls.py
from django.urls import include, path
from rest_framework import routers

from catalog import api, views

app_name = "catalog"

router = routers.DefaultRouter()
router.register("spots", api.CatalogViewSet)

router_main_image = routers.DefaultRouter()
router_main_image.register("main_images", api.MainImageViewSet)

router_regions = routers.DefaultRouter()
router_regions.register("regions", api.RegionViewSet)

urlpatterns = [
    path(
        "",
        views.SpotListView.as_view(),
        name="spot_list",
    ),
    path(
        "<int:pk>/",
        views.SpotDetailView.as_view(),
        name="spot_detail",
    ),
    path(
        "create/",
        views.CreateFishingPlaceView.as_view(),
        name="create_spot",
    ),
    path(
        "created/",
        views.CreatedPlace.as_view(),
        name="created_spot",
    ),
    path(
        "created/<int:pk>/edit/",
        views.EditPalce.as_view(),
        name="edit_palce",
    ),
    path(
        "region/<int:region>/",
        views.RegionView.as_view(),
        name="region",
    ),
    path(
        "api/",
        include(router.urls),
    ),
    path(
        "api/",
        include(router_main_image.urls),
    ),
    path(
        "api/",
        include(router_regions.urls),
    ),
    path(
        "api-auth/",
        include(
            "rest_framework.urls",
            namespace="rest_framework",
        ),
    ),
]

OnTheHook/map/urls.py
from django.urls import path
from map import views

app_name = "map"

urlpatterns = [
    path(
        "",
        views.MapView.as_view(),
        name="map",
    ),
]

OnTheHook/catalog/models.py
import re

from ckeditor.fields import RichTextField
from django.core import validators
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import dateformat, timezone
from django.utils.safestring import mark_safe
from sorl.thumbnail import get_thumbnail

from catalog.validators import MaxWordsValidator

__all__ = []

REGEX = re.compile(r"[^\w]")


def spot_directory_path(instance, filename):
    return f"catalog/{instance.spot.id}/{filename}"


class Region(models.Model):
    region = models.CharField(
        verbose_name="регион",
        max_length=150,
        validators=[validators.MaxLengthValidator(150)],
        help_text="Введите регион",
        unique=True,
    )

    class Meta:
        verbose_name = "регион"
        verbose_name_plural = "регионы"

    def __str__(self):
        return self.region


class Spot(models.Model):
    user = models.ForeignKey(
        "users.User",
        verbose_name="пользователь",
        on_delete=models.CASCADE,
    )
    region = models.ForeignKey(
        "Region",
        on_delete=models.CASCADE,
        related_name="spot_region",
        related_query_name="spot_region",
        default=None,
        blank=True,
        null=True,
        verbose_name="Регион",
        help_text="Выберите или добавьте регион",
    )
    name = models.CharField(
        verbose_name="название",
        max_length=150,
        validators=[validators.MaxLengthValidator(150)],
        help_text="Введите название",
    )
    text = RichTextField(
        verbose_name="Текст",
        help_text="Введите описание",
        validators=[MaxWordsValidator(1000)],
    )
    lat = models.FloatField(
        verbose_name="широта",
        help_text="Введите широту",
    )
    lon = models.FloatField(
        verbose_name="долгота",
        help_text="Введите долготу",
    )
    date_created = models.DateTimeField(
        verbose_name="дата создания места",
        auto_now_add=True,
    )
    status_free = models.BooleanField(
        verbose_name="платное",
        null=True,
    )
    is_active = models.BooleanField(
        verbose_name="активный",
        null=True,
        default=False,
    )

    class Meta:
        ordering = ("region",)
        verbose_name = "объект"
        verbose_name_plural = "объекты"

    def clean(self) -> None:
        if (
            not self.id
            and Spot.objects.filter(
                lat__gt=self.lat - 0.005,
                lat__lt=self.lat + 0.005,
                lon__gt=self.lon - 0.005,
                lon__lt=self.lon + 0.005,
            ).exists()
        ):
            raise ValidationError("Объект уже существует")
        return super().clean()

    def save(
        self,
        *args,
        **kwargs,
    ):
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    def forced_update(self, kwds):
        for key in kwds:
            self.__dict__[key] = kwds[key]


class SpotMainImage(models.Model):
    def upload_to(self, file_name):
        type_image = file_name.split(".")[1]
        return (
            f"reservoir/{self.spot.user.id}/{self.spot_id}/"
            f"{dateformat.format(timezone.now(), 'd_m_y_H_i', )}.{type_image}"
        )

    spot = models.OneToOneField(
        "Spot",
        on_delete=models.CASCADE,
        verbose_name="озеро",
        related_name="spot_mainimage",
        related_query_name="spot_mainimage",
    )

    image = models.ImageField(
        upload_to=upload_to,
        verbose_name="изображение",
    )

    @property
    def get_300x300px(self):
        return get_thumbnail(self.image, "300x300", crop="center", quality=51)

    def image_tmb(self):
        if self.image:
            return mark_safe(
                f"<img src=/media/{self.get_300x300px}/>",
            )
        return "Изображение не найдено/отсутсвует"

    @property
    def alter_img(self):
        if self.image:
            return f"{self.get_300x300px}"
        return None

    image_tmb.short_description = "превью"
    image_tmb.allow_tags = True

    fields = ["image_tmb"]

    def __str__(self):
        return self.image.url

    class Meta:
        verbose_name = "изображение"
        verbose_name_plural = "изображения"


class SpotImages(models.Model):
    def upload_to(self, file_name):
        type_image = file_name.split(".")[1]
        return (
            f"reservoir/{self.spot.user.id}/{self.spot_id}/"
            f"{dateformat.format(timezone.now(), 'd_m_y_H_i', )}.{type_image}"
        )

    spot = models.ForeignKey(
        "Spot",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="товар",
        related_query_name="spot_images",
        related_name="spot_images",
    )

    image = models.ImageField(
        upload_to=upload_to,
        null=True,
        blank=True,
        verbose_name="изображение",
    )

    @property
    def get_300x300px(self):
        return get_thumbnail(
            self.image,
            "300x300",
            crop="center",
            quality=51,
        )

    def image_tmb(self):
        if self.image:
            return mark_safe(
                f"<img src=/media/{self.get_300x300px}/>",
            )
        return "Изображение не найдено/отсутсвует"

    @property
    def alter_img(self):
        if self.image:
            return f"/media/{self.get_300x300px}"
        return None

    image_tmb.short_description = "превью"
    image_tmb.allow_tags = True

    fields = ["image_tmb"]

    def __str__(self):
        return self.image.url

    class Meta:
        verbose_name = "изображения"
        verbose_name_plural = "изображения"

OnTheHook/catalog/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms

from catalog.models import Spot

__all__ = []


class SpotForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["images"].widget.attrs["multiple"] = True
        self.fields["images"].widget.attrs["required"] = False
        for field in self.visible_fields():
            field.field.widget.attrs["class"] = "form-control"

    images = forms.ImageField(
        label="Картинки",
        required=False,
    )

    class Meta:
        model = Spot
        exclude = (
            Spot.user.field.name,
            Spot.date_created.field.name,
            Spot.is_active.field.name,
        )

        widgets = {Spot.text.field.name: CKEditorWidget()}

OnTheHook/catalog/views.py
from django.contrib import messages
from django.db.models import Prefetch
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView, ListView, View
from django.views.generic.edit import FormMixin
from rating.forms import SpotRatingForm
from rating.models import RatingImages, SpotRating

from catalog.forms import SpotForm
from catalog.models import Region, Spot, SpotImages, SpotMainImage


__all__ = [
    "SpotListView",
    "SpotDetailView",
    "CreateFishingPlaceView",
]


class SpotListView(ListView):
    template_name = "catalog/catalog.html"

    def get(self, request):
        spots = (
            Spot.objects.select_related("spot_mainimage", "region")
            .filter(
                is_active=True,
            )
            .only("name", "region")
        )
        regions = Region.objects.only("region", "id")
        context = {"spots": spots, "regions": regions}
        return render(request, "catalog/catalog.html", context)

    def post(self, request):
        region = dict(request.POST)["region"][0]
        return redirect(f"/catalog/region/{region}")


class RegionView(ListView):
    def get(self, request, region):
        spots = (
            Spot.objects.select_related("spot_mainimage", "region")
            .filter(is_active=True, region=region)
            .only("name", "region")
        )
        regions = Region.objects.only("region", "id")
        context = {"spots": spots, "regions": regions, "region": region}
        return render(request, "catalog/region_list.html", context)

    def post(self, request, region):
        region = dict(request.POST)["region"][0]
        return redirect(f"/catalog/region/{region}")


class SpotDetailView(DetailView, FormMixin):
    model = Spot
    template_name = "catalog/detail.html"
    context_object_name = "spot_info"
    pk_url_kwarg = "pk"
    form_class = SpotRatingForm
    context = {}

    def get(self, request, pk):
        instance = None
        spot = self.model.objects.filter(id=pk)
        if not spot.first() or not spot.first().__getattribute__("is_active"):
            if not request.user.is_moderator or not request.user.is_superuser:
                return render(request, "404.html", {})
        form = SpotRatingForm(
            None,
            instance=instance,
        )
        self.context["form"] = form
        self.context["spot_info"] = (
            spot.select_related("spot_mainimage")
            .prefetch_related(
                Prefetch(
                    "spot_images",
                    queryset=SpotImages.objects.only("image"),
                ),
            )
            .first()
        )

        self.context["users_comments"] = (
            SpotRating.objects.filter(
                spot_id=pk,
            )
            .select_related("user")
            .prefetch_related(
                Prefetch(
                    "rating_images",
                    queryset=RatingImages.objects.only("image"),
                ),
            )
            .only(
                "user__username",
                "user__avatar",
                "mark",
                "comment",
                "created_at",
            )
        )

        return render(request, self.template_name, self.context)

    def post(self, request, pk):
        form = SpotRatingForm(request.POST or None)
        if request.method == "POST" and form.is_valid():
            if request.user.is_authenticated:
                if form.cleaned_data.get("mark") in (
                    5,
                    4,
                    3,
                    2,
                    1,
                ):
                    del form.cleaned_data["images"]
                    rating_spot = SpotRating.objects.update_or_create(
                        user=request.user,
                        spot_id=pk,
                        defaults=form.cleaned_data,
                    )
                    if request.FILES.get("images"):
                        RatingImages.objects.create(
                            spot=rating_spot[0],
                            image=request.FILES.get("images"),
                        )
                    messages.success(request, "Рейтинг выставлен")
                elif form.cleaned_data.get("mark") == 0:
                    SpotRating.objects.filter(
                        user=request.user,
                        spot_id=pk,
                    ).delete()
                    messages.success(request, "Рейтинг удалён")
                else:
                    messages.error(request, "Ошибка обработки формы!")
        return redirect(self.get_success_url(**self.kwargs))

    def get_success_url(self, **kwargs):
        return reverse("catalog:spot_detail", kwargs=self.kwargs)


class CreateFishingPlaceView(View, FormMixin):
    template_name = "catalog/create.html"
    model = Spot
    context = {}
    form_class = SpotForm
    success_url = "/catalog/create/"

    def get(self, request):
        self.context["form"] = self.form_class(
            None,
            instance=self.request.user,
        )

        return render(request, "catalog/create.html", self.context)

    def form_valid(self, form):
        images = self.request.FILES.getlist("images")
        if len(images) < 2:
            messages.error(self.request, "Добавьте несколько картинок места!")
            return render(self.request, "catalog/create.html", self.context)

        form_save = form.save(commit=False)
        form_save.user = self.request.user
        form_save.save()

        SpotMainImage.objects.create(spot=form_save, image=images[0])
        for image in images[1:]:
            SpotImages.objects.create(spot=form_save, image=image)
        messages.success(self.request, "Водоём добавлен!")
        return super().form_valid(form)

    def post(self, request):
        form = SpotForm(request.POST)
        if form.is_valid():
            return self.form_valid(form)
        self.context["form"] = form
        messages.error(request, "Ошибка=)")
        return render(request, "catalog/create.html", self.context)


class CreatedPlace(View):
    template_name = "catalog/created_spots.html"
    context = {}
    model = Spot

    def get(self, request):
        spots = self.model.objects.filter(user=request.user)
        self.context["spots"] = spots
        return render(request, self.template_name, self.context)


class EditPalce(View):
    template_name = "catalog/edit_place.html"
    model = Spot
    form_class = SpotForm
    context = {}
    pk_url_kwarg = "pk"

    def get(self, request, pk):
        model = self.model.objects.get(id=pk, user=request.user)
        self.context["form"] = self.form_class(None, instance=model)
        return render(request, self.template_name, self.context)

    def post(self, request, pk):
        form = SpotForm(request.POST)
        form.is_valid()
        if request.user.is_authenticated:
            self.model.objects.update_or_create(
                user=request.user,
                id=pk,
                defaults=form.cleaned_data,
            )
        self.context["form"] = form
        return render(request, self.template_name, self.context)

OnTheHook/templates/catalog/catalog.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% block title %}<title>Каталог</title>{% endblock %}
<div class="container">
  {% if request.user.is_authenticated %}
  <div class="row">
    <div class="col-md-8">
      <p class="h3">Знаешь клёвые места и готов поделиться?</p>
    </div>
    <div class="col-md-4">
      <a href="{% url 'catalog:create_spot'%}" class="btn btn-primary mb-4">Поделись
        своим
        клёвым местом</a>
    </div>
   </div>
    {% endif %}
    <form action="." method="post">
      {% csrf_token %}
      <div class="row mb-4">
        <div class="col-md-8">
          <select class="form-select" name="region">
            <option value="1099" selected>Выберите регион</option>
            {% for region in regions %}
            <option value="{{ region.id }}">{{ region.region }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="col-md-4">
          <input type="submit" class="btn btn-secondary" value="Выбрать" title="Выбрать"/>
        </div>
      </div>
    </form>

  <div class="row">
    {% for spot in spots %}
    {% ifchanged spot.region %}
    <h2 class="col-md-12 text-center mb-3">{{ spot.region }}</h2>
    {% endifchanged %}
    <div class="col-md-4 mb-4">
      <div class="card" style="width: 18vrem;">
        <img src="{{ spot.spot_mainimage.image.url }}" class="main-img-catalog" alt="..."/>
        <div class="card-body">
          <h5 class="card-title">{{ spot.name }}</h5>
          <p class="card-text">{{ spot.text|truncatewords_html:5|safe }}</p>
          <a href="{% url 'catalog:spot_detail' spot.id %}" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
    </div>
    {% empty %}
    <p>Ещё нет клёвых мест:(</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

OnTheHook/templates/catalog/create.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
{% block title %}<title>Добавление нового места</title>{% endblock %}
<div class="container">
  {{form.media}}
  {% include 'includes/spot_form.html' %}
</div>

{% endblock %}

OnTheHook/templates/catalog/created_spots.html
{% extends 'base.html' %}
{% block content %}
  {% load static %}
{% block title %}<title>Добавленные места</title>{% endblock %}

  {% for spot in spots %}
  <div class="col-md-4 mb-4">
    <div class="card" style="width: 18vrem;">
      <img src="{{ spot.spot_mainimage.image.url }}" class="card-img-top" alt="..." />
      <div class="card-body">
        <h5 class="card-title">{{ spot.name }}</h5>
        <p class="card-text">{{ spot.region|truncatewords_html:10|safe }}</p>
        <a href="{% url 'catalog:edit_palce' spot.id %}" class="btn btn-primary">Редактировать</a>
      </div>
      {% empty %}
      <h1>Вы пока не добавли ни одного места</h1>
    {% endfor %}
  </div>
{% endblock %}

OnTheHook/templates/catalog/detail.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% block title %}<title>{{ spot_info.name }}</title>{% endblock %}
<div class="container">
  <div>
    <h1 class="h1 mb-4">{{ spot_info.name }}</h1>
    <div id="carouselExample" class="carousel slide">

      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{{spot_info.spot_mainimage.image.url}}" class="d-block w-100 carousel-image" alt="...">
        </div>
        {% for image in spot_info.spot_images.all %}
        <div class="carousel-item">
          <img src="{{image.image.url}}" class="d-block w-100 carousel-image" alt="...">
        </div>
        {% endfor %}
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <div class="py-3">
      <div class="mb-3">
        <p>{{ spot_info.text|safe }}</p>
      </div>
      <p class="h4"><a class="btn btn-primary"
          href="https://yandex.ru/maps/?ll={{ spot_info.lon }}%2C{{ spot_info.lat }}&mode=search&sll={{ spot_info.lon }}%2C{{ spot_info.lat }}&text={{ spot_info.lat }}%2C{{ spot_info.lon }}&z=13.63">В
          путь</a>
      </p>
      <p class="mb-1">Широта: <span>{{ spot_info.lat }}</span></p>
      <p class="mb-1">Долгота: <span>{{ spot_info.lon }}</span></p>
      {% if request.user.is_authenticated %}
      <div class="accordion accordion-flush" id="accordionFlushExample">
        <div class="accordion-item">
          <h2 class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
              data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
              Форма для отзыва!
            </button>
          </h2>
          <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
            {% include "includes/auth_form.html" %}
          </div>
        </div>
      </div>
      {%endif%}
      <div class="py-3">
        <p class="h4">Отчёты о рыбалке</p>
        <div class="p-2 bg-body-tertiary mb-2 rounded-2">
          {% for comment in users_comments %}
          <div>
            <h3><img src="{{comment.user.get_avatar}}" class="img-thumbnail rounded-circle avatar" alt="" height="50px"
                width="60px">{{comment.user.username}}</h3>


          </div>
          <p class="">{{ comment.comment }}</p>
          <div class="row">
            {% for image in comment.rating_images.all %}
            <div class="col-md-3">
              <img src="{{ image.image.url }}" class="d-block img-thumbnail gallery-img" alt="...">
            </div>
            {% endfor %}
          </div>
          <p class="fw-light">{{comment.created_at}}</p>
          <hr>
          {%empty%}
          <p class="text-muted">Будь вторым, кто обуздает это место!</p>

          {% endfor %}
        </div>

      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}

OnTheHook/templates/catalog/edit_place.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% block title %}<title>Редактирование</title>{% endblock %}
<div class="container">
  {{ form.media }}
  {% include 'includes/spot_form.html' %}
</div>
{% endblock %}

OnTheHook/templates/catalog/region_list.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% block title %}<title>Каталог</title>{% endblock %}
<div class="container">
  {% if request.user.is_authenticated %}
  <div class="row">
    <div class="col-md-8">
      <p class="h3">Знаешь клёвые места и готов поделиться?</p>
    </div>
    <div class="col-md-4">
      <a href="{% url 'catalog:create_spot'%}" class="btn btn-primary mb-4">Поделись
        своим
        клёвым местом</a>
    </div>
  </div>
  {% endif %}
  <form action="." method="post">
    {% csrf_token %}
    <div class="row mb-4">
      <div class="col-md-8">
        <select class="form-select" name="region">
          {% for reg in regions %}
          {% if reg.id == region %}
          <option value="{{ reg.id }}" selected>{{ reg.region }}</option>
          {% else %}
          <option value="{{ reg.id }}">{{ reg.region }}</option>
          {% endif %}
          {% endfor %}
        </select>
      </div>
      <div class="col-md-4">
        <input type="submit" class="btn btn-secondary" value="Выбрать" title="Выбрать"/>
        <a class="btn btn-secondary" href="{% url 'catalog:spot_list' %}">Все регионы</a>
      </div>
    </div>
  </form>


  <div class="row">
    {% for spot in spots %}
    <div class="col-md-4 mb-4">
      <div class="card" style="width: 18vrem;">
        <img src="{{ spot.spot_mainimage.image.url }}" class="main-img-catalog" alt="..."/>
        <div class="card-body">
          <h5 class="card-title">{{ spot.name }}</h5>
          <p class="card-text">{{ spot.region|truncatewords_html:10|safe }}</p>
          <a href="{% url 'catalog:spot_detail' spot.id %}" class="btn btn-primary">Подробнее</a>
        </div>
      </div>
    </div>
    {% empty %}
    <p>Ещё нет клёвых мест:(</p>
    {% endfor %}
  </div>
</div>
{% endblock %}