OnTheHook/OnTheHook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path(
        "",
        include("homepage.urls"),
    ),
    path(
        "auth/",
        include("users.urls"),
    ),
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("social_django.urls"),
    ),
    path(
        "catalog/",
        include("catalog.urls"),
    ),
    path(
        "moderation/",
        include("moderation.urls"),
    ),
    path(
        "map/",
        include("map.urls"),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

OnTheHook/catalog/urls.py
from django.urls import include, path
from rest_framework import routers

from catalog import api, views

app_name = "catalog"

router = routers.DefaultRouter()
router.register("spots", api.CatalogViewSet)

router_main_image = routers.DefaultRouter()
router_main_image.register("main_images", api.MainImageViewSet)

router_regions = routers.DefaultRouter()
router_regions.register("regions", api.RegionViewSet)

urlpatterns = [
    path(
        "",
        views.SpotListView.as_view(),
        name="spot_list",
    ),
    path(
        "<int:pk>/",
        views.SpotDetailView.as_view(),
        name="spot_detail",
    ),
    path(
        "create/",
        views.CreateFishingPlaceView.as_view(),
        name="create_spot",
    ),
    path(
        "created/",
        views.CreatedPlace.as_view(),
        name="created_spot",
    ),
    path(
        "created/<int:pk>/edit/",
        views.EditPalce.as_view(),
        name="edit_palce",
    ),
    path(
        "region/<int:region>/",
        views.RegionView.as_view(),
        name="region",
    ),
    path(
        "api/",
        include(router.urls),
    ),
    path(
        "api/",
        include(router_main_image.urls),
    ),
    path(
        "api/",
        include(router_regions.urls),
    ),
    path(
        "api-auth/",
        include(
            "rest_framework.urls",
            namespace="rest_framework",
        ),
    ),
]

OnTheHook/homepage/urls.py
from django.urls import path

from homepage import views

app_name = "homepage"

urlpatterns = [
    path("", views.HomepageView.as_view(), name="homepage"),
]

OnTheHook/map/urls.py
from django.urls import path
from map import views

app_name = "map"

urlpatterns = [
    path(
        "",
        views.MapView.as_view(),
        name="map",
    ),
]

OnTheHook/homepage/views.py
from django.views.generic import TemplateView

__all__ = []


class HomepageView(TemplateView):
    template_name = "homepage/index.html"

OnTheHook/templates/homepage/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="container">
  <div class="row flex-lg-row-reverse align-items-center pb-5">
    <div class="col-10 col-sm-8 col-lg-6 mb-4">
      <img src="{% static 'image/hero.svg'%}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500">
    </div>
    <div class="col-lg-6">
      <h1 class="display-5 fw-bold lh-1 mb-3">Клёвое место</h1>
      <p class="lead">Много клёвых мест на одном сайте. Выезжайте на рыбалку прямо сейчас!</p>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary btn-lg px-4 me-md-2" href="{% url 'catalog:spot_list' %}">Каталог</a>
        <a class="btn btn-outline-secondary btn-lg px-4" href="{% url 'map:map' %}">Карта</a>
      </div>
    </div>
  </div>
</div>

<div class="bg-body-tertiary">
  <div class="container">
    <div class="row align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="{% static 'image/chatbot.svg'%}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="500"
             height="400">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold lh-1 mb-3">Чат-бот "Клёвое место"</h1>
        <p class="lead">Все клёвые места в твоём смартфоне.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
          <a class="btn btn-primary btn-lg px-4 me-md-2" href="https://t.me/FishPlace_lyceum_bot">Открыть чат бот</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}