OnTheHook/OnTheHook/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path(
        "",
        include("homepage.urls"),
    ),
    path(
        "auth/",
        include("users.urls"),
    ),
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "",
        include("social_django.urls"),
    ),
    path(
        "catalog/",
        include("catalog.urls"),
    ),
    path(
        "moderation/",
        include("moderation.urls"),
    ),
    path(
        "map/",
        include("map.urls"),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT,
)
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

OnTheHook/map/urls.py
from django.urls import path
from map import views

app_name = "map"

urlpatterns = [
    path(
        "",
        views.MapView.as_view(),
        name="map",
    ),
]

OnTheHook/users/urls.py
from django.contrib.auth import views as djangoviews
from django.contrib.auth.decorators import login_required
from django.urls import path

import users.views as views

app_name = "users"

urlpatterns = [
    path(
        "profile/",
        login_required(views.ProfileView.as_view()),
        name="profile",
    ),
    path(
        "register/",
        views.RegisterView.as_view(),
        name="register",
    ),
    path(
        "login/",
        djangoviews.LoginView.as_view(
            template_name="users/auth/login.html",
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "logout/",
        djangoviews.LogoutView.as_view(
            template_name="users/auth/logout.html",
        ),
        name="logout",
    ),
    path(
        "password_change/",
        djangoviews.PasswordChangeView.as_view(
            template_name="users/auth/password_change.html",
        ),
        name="change_password",
    ),
    path(
        "password_change/done/",
        djangoviews.PasswordChangeDoneView.as_view(
            template_name="users/auth/password_change_done.html",
        ),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        djangoviews.PasswordResetView.as_view(
            template_name="users/auth/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        djangoviews.PasswordResetDoneView.as_view(
            template_name="users/auth/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        djangoviews.PasswordResetConfirmView.as_view(
            template_name="users/auth/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        djangoviews.PasswordResetCompleteView.as_view(
            template_name="users/auth/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

OnTheHook/templates/includes/auth_form.html
{% for message in messages %}
    <div class="text-center">
  {% if "success" in message.tags %}
    <div class="success-message alert alert-success">{{ message }}</div>
  {% elif "warning" in message.tags %}
    <div class="warning-message alert alert-warning">{{ message }}</div>
  {% elif "error" in message.tags %}
    <div class="error-message alert alert-danger">{{ message }}</div>
  {% endif %}
  </div>
{% endfor %}
{% with request.resolver_match.view_name as view_name %}
<div class="d-flex {% if view_name != 'catalog:spot_detail' %}justify-content-center{% endif %}">

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-3">
      {% for field in form %}
      <div class="form-label {% if field.errors %}error{% endif %}">
        <label class="control-label" for="{{field.id_for_label}}">{{ field.label|capfirst }}</label>
        <div class="controls">
          {{field}}
          <h6>{{field.help_text}}</h6>
          {% if form.errors %}
            <span class="help-inline">
              {% for error in field.errors %}
                <div class="text-warning">
                  {{ error|escape }}
                </div> 
              {% endfor %}
            </span>
          {% endif %}
        </div>
      </div>
      {% endfor %}
      <div class="{% if view_name != 'catalog:spot_detail' and view_name != 'catalog:create_spot' %}text-center{% endif %}">
        <input type="submit" class="btn btn-primary" value="Подтвердить" title="Подтвердить"/>
      </div>
    </div>
  </form>
  {% endwith %}
</div>

OnTheHook/templates/includes/footer.html
{% load static %}
<footer class="dark mt-4">
  <div class="container">
    <div class="d-flex flex-wrap justify-content-between align-items-center py-3">
      <p class="col-md-4 mb-0 text-muted"><img src="{% static '/image/logo2.png'%}" width="150"></p>

      <a href="/"
         class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32">
          <use xlink:href="#bootstrap"></use>
        </svg>
      </a>
      {% with request.resolver_match.view_name as view_name %}
      <ul class="nav col-md-4 justify-content-end">
        <li class="nav-item"><a href="{% if view_name != 'catalog:spot_list' %}
                    {% url 'catalog:spot_list' %}{% else %}#
                  {% endif %}" class="nav-link px-2 footer-link">Каталог</a></li>
        <li class="nav-item"><a href="{% if view_name != 'map:map' %}
                    {% url 'map:map' %}{% else %}#
                  {% endif %}" class="nav-link px-2 footer-link">Карта</a></li>
      </ul>
      {% endwith %}
    </div>
  </div>
</footer>

OnTheHook/templates/includes/header.html
{% load static %}
<header class="bg-body-tertiary mb-4">
  <div class="container">
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="/"><img src="{% static '/image/logo4.png' %}" width="150"/></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
            class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% with request.resolver_match.view_name as view_name %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'homepage:homepage' %}active{% endif %}"
                 href="{% if view_name != 'homepage:homepage' %}{% url 'homepage:homepage' %}{% else %}#
                  {% endif %}">
                Главная
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'catalog:spot_list' %}active{% endif %}"
                 href="{% if view_name != 'catalog:spot_list' %}
                    {% url 'catalog:spot_list' %}{% else %}#
                  {% endif %}">
                Каталог
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'map:map' %}active{% endif %}"
                 href="{% if view_name != 'map:map' %}
                    {% url 'map:map' %}{% else %}#
                  {% endif %}">
                Карта
              </a>
            </li>
          </ul>
          {% endwith %}
          <div class="d-flex">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
              </li>
              {% if request.user.is_superuser %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Администрирование</a>
              </li>
              {% endif %}
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Вход</a>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>

OnTheHook/templates/includes/special_test.html
<div class="container mt-1">
  <div id="map" style="height: 800px;"></div>
  <span id="id_user_region" value="{{ request.user.location }}"></span>
  <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&apikey=88929720-ecd9-41a2-871e-ce817fd43182&lang=ru_RU"></script>
  <script>
    function init() {
      var lat = document.getElementById('id_lat').value
      var lon = document.getElementById('id_lon').value
      console.log(lat == "")
      var center, region
    
      if (lat != "") {
        center = [lat, lon];
        zoom = 18;
      } else {
        center = [45.04344559937834,41.96065721112236];
        zoom = 10;
      }
      const myMap = new ymaps.Map('map', {
        center: center,
        zoom: zoom,
      })
      const addMarkers = (dataFromServer) => {
        const places = dataFromServer.map(item => new ymaps.Placemark(
          [item.lat, item.lon],
          {
            balloonContent: '<div class="mb-1"><img src="' + item.img + '" style="width: 110px; height: auto;"></div><a class="btn btn-primary" href="/catalog/' + item.id + '">Подробнее</a>',
            iconCaption: item.name
          },
          {
            preset: 'islands#governmentCircleIcon',
            iconColor: '#3b5998'
          }
        ))

        for (const place of places) {
          myMap.geoObjects.add(place)
        }
      }

      fetch('/catalog/api/spots/')
        .then((response) => response.json())
        .then((data) => {
          console.log(data)
          addMarkers(data)
        })
      myMap.events.add('click', function (e) {
        var coords = e.get('coords')
        var lat = document.getElementById('id_lat')
        var lon = document.getElementById('id_lon')
        lat.value = coords[0]
        lon.value = coords[1]
      })
    }
    
    ymaps.ready(init)
  </script>
</div>

OnTheHook/templates/includes/spot_form.html
{% for message in messages %}
  {% if 'success' in message.tags %}
    <div class="success-message alert alert-success">{{ message }}</div>
  {% elif 'warning' in message.tags %}
    <div class="warning-message alert alert-warning">{{ message }}</div>
  {% elif 'error' in message.tags %}
    <div class="error-message alert alert-danger">{{ message }}</div>
  {% endif %}
{% endfor %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    {% for field in form %}
      <div class="form-label {% if field.errors %}{% endif %}">
        <label class="control-label" for="{{ field.id_for_label }}">{{ field.label|capfirst }}</label>
        <div class="controls">
          {{ field }}
          {% if field.name == 'region' %}
            {% include "includes/special_test.html" %}
          {% endif %}
          <h6>{{ field.help_text }}</h6>
          {% if form.errors %}
            <span class="help-inline">
              {% for error in field.errors %}
                <div class="text-warning">{{ error|escape }}</div>
              {% endfor %}
            </span>
          {% endif %}
        </div>
      </div>
    {% endfor %}

    <input type="submit" class="btn btn-primary" value="подтвердить" title="подтвердить" />
  </div>
</form>